import { Inter } from 'next/font/google';
import "./globals.css";
import ContactIcon from "@components/ContactIcon";
import { metadata } from './metadata';
const inter = Inter({
  subsets: ['latin'],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export { metadata };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${inter.variable} app`} >
        <ContactIcon />
        {children}
      </body>
    </html>
  );
}
