import { Inter } from 'next/font/google';
import "./globals.css";
import ContactIcon from "@components/ContactIcon";
import { Sitemetadata } from './metadata';
import { GoogleAnalytics } from 'nextjs-google-analytics';
const inter = Inter({
  subsets: ['latin'],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata={ Sitemetadata };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${inter.variable} app`} >
          <GoogleAnalytics trackPageViews gaMeasurementId={process.env.GA_ID}/>
        <ContactIcon />
        {children}
      </body>
    </html>
  );
}
